<?php
$linkedinProfileAttribute = $block->getCustomer()->getCustomAttribute('linkedin_profile');
if ($linkedinProfileAttribute) {
    $linkedinProfileValue = $linkedinProfileAttribute->getValue();
} else {
    $linkedinProfileValue = '';
}
?>
<fieldset class="fieldset info" <?=$block->getLinkedinVisibility()?>>
    <div class="field linkedin_profile <?=$block->getLinkedinIsRequired()?>">
        <label class="label" for="linkedin_profile"><span><?= $block->escapeHtml(__('Linkedin Profile')) ?></span></label>
        <div class="control">
            <input type="text" name="linkedin_profile" id="linkedin_profile" data-input="linkedin_profile" value="<?=$linkedinProfileValue?>" title="<?= $block->escapeHtmlAttr(__('Linkedin Profile')) ?>" class="input-text" data-validate="{'validate-url':true, 'validate-length':250}" />
        </div>
    </div>
</fieldset>