<fieldset class="fieldset info">
    <div class="field linkedin_profile">
        <label class="label" for="linkedin_profile"><span><?= $block->escapeHtml(__('Linkedin Profile')) ?></span></label>
        <div class="control">
            <input type="text" name="linkedin_profile" id="linkedin_profile" data-input="linkedin_profile" value="" title="<?= $block->escapeHtmlAttr(__('Linkedin Profile')) ?>" class="input-text" data-validate="{'validate-url':true}" />
        </div>
    </div>
</fieldset>